version: '3.8'

services:
  app:
    build: .
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/brev_ly
      - PORT=3333
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=brev_ly
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
